# Azure Durable Functions (Backend) - CI/CD Pipeline
# GitHub Flow + Release Branches deployment with semantic versioning

# Reference templates from shared repository
resources:
  repositories:
    - repository: templates
      type: git
      name: azure-devops-templates-test
      endpoint: template-connect
      ref: refs/heads/main

trigger:
  branches:
    include:
      - main
      - release/*
      - hotfix/*
  paths:
    include:
      - app2-functions/**
      - pipelines/app2-functions-pipeline.yml

pr:
  branches:
    include:
      - main
      - release/*
      - hotfix/*
  paths:
    include:
      - app2-functions/**

variables:
  # Import shared version configuration from repo
  # Note: version.yml is NOT in trigger paths - version bumps alone don't trigger rebuilds
  # - template: ../version.yml
  
  - name: pythonVersion
    value: '3.12'
  - name: workingDirectory
    value: 'app2-functions'
  - name: artifactName
    value: 'function-app'
  
  # Import environment-specific variable groups based on branch
  # Create these variable groups in Azure DevOps Library:
  # - function-app-dev: contains azureSubscription, appName, resourceGroup for dev
  # - function-app-test: contains azureSubscription, appName, resourceGroup for test (stage environment)
  # - function-app-prd: contains azureSubscription, appName, resourceGroup for prd
  
  # Load test & prd variable groups for release/hotfix branches
  - ${{ if and(ne(variables['Build.Reason'], 'PullRequest'), or(startsWith(variables['Build.SourceBranch'], 'refs/heads/release/'), startsWith(variables['Build.SourceBranch'], 'refs/heads/hotfix/'))) }}:
    - group: function-app-test
    - group: function-app-prd
  
  # Load dev variable group for main branch
  - ${{ if and(ne(variables['Build.Reason'], 'PullRequest'), eq(variables['Build.SourceBranchName'], 'main')) }}:
    - group: function-app-dev

stages:
  # Build Stage (also handles PR validation)
  - stage: Build
    displayName: 'Build & Validate'
    jobs:
      - job: Build
        displayName: 'Build Function App'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          # Build Application with automatic versioning and git tagging
          # For PRs: runs tests and linting only (no versioning/tagging)
          # For deployments: runs full build with versioning, security scanning, and tagging
          - template: build-templates/build-and-validate-template.yml@templates
            parameters:
              pythonVersion: $(pythonVersion)
              workingDirectory: $(workingDirectory)
              artifactName: $(artifactName)
              runTests: true
              runLinting: true
              # runSecurityScan: ${{ ne(variables['Build.Reason'], 'PullRequest') }}

  # DEPLOYMENT STAGES - Deploy Same Artifact
  - ${{ if ne(variables['Build.Reason'], 'PullRequest') }}:
    
    # Deploy to Test/Stage (release/* and hotfix/* branches only)
    - template: deploy-templates/deploy-environment-template.yml@templates
      parameters:
        environmentName: 'test'
        azureSubscription: $(azureSubscription)
        appName: $(appName)
        slotName: 'staging'
        artifactName: $(artifactName)
        resourceGroup: $(resourceGroup)
        appType: 'functionApp'
        dependsOn: ['Build']
        condition: |
          or(
            startsWith(variables['Build.SourceBranch'], 'refs/heads/release/'),
            startsWith(variables['Build.SourceBranch'], 'refs/heads/hotfix/')
          )

    # Deploy to Production (release/* and hotfix/* branches, after test)
    - template: deploy-templates/deploy-environment-template.yml@templates
      parameters:
        environmentName: 'prd'
        azureSubscription: $(azureSubscription)
        appName: $(appName)
        slotName: 'staging'
        artifactName: $(artifactName)
        resourceGroup: $(resourceGroup)
        appType: 'functionApp'
        dependsOn: ['Deploy_test']
        condition: |
          or(
            startsWith(variables['Build.SourceBranch'], 'refs/heads/release/'),
            startsWith(variables['Build.SourceBranch'], 'refs/heads/hotfix/')
          )

    # Deploy to Dev (main branch merges only)
    - template: deploy-templates/deploy-environment-template.yml@templates
      parameters:
        environmentName: 'dev'
        azureSubscription: $(azureSubscription)
        appName: $(appName)
        slotName: 'staging'
        artifactName: $(artifactName)
        resourceGroup: $(resourceGroup)
        appType: 'functionApp'
        dependsOn: ['Build']
        condition: eq(variables['Build.SourceBranchName'], 'main')
