# Azure Durable Functions (Backend) - CI/CD Pipeline
# GitFlow-based deployment with semantic versioning

# Reference templates from shared repository
resources:
  repositories:
    - repository: templates
      type: git
      name: azure-devops-templates
      ref: refs/heads/main

trigger:
  branches:
    include:
      - main
      - develop
      - release/*
      - hotfix/*
  paths:
    include:
      - app2-functions/**
      - pipelines/app2-functions-pipeline.yml

pr:
  branches:
    include:
      - main
      - develop
      - release/*
      - hotfix/*
  paths:
    include:
      - app2-functions/**

variables:
  # Import shared version configuration from repo
  # Note: version.yml is NOT in trigger paths - version bumps alone don't trigger rebuilds
  # - template: ../version.yml
  
  - name: pythonVersion
    value: '4.0'
  - name: workingDirectory
    value: 'app2-functions'
  - name: artifactName
    value: 'function-app'
  
  # Import environment-specific variable groups based on branch
  # Create these variable groups in Azure DevOps Library:
  # - function-app-dev: contains appName, resourceGroup, azureSubscription for dev
  # - function-app-test: contains appName, resourceGroup, azureSubscription for test
  # - function-app-prd: contains appName, resourceGroup, azureSubscription for prd
  # Note: Variable groups not needed for PR validation builds
  - ${{ if and(ne(variables['Build.Reason'], 'PullRequest'), eq(variables['Build.SourceBranchName'], 'develop')) }}:
    - group: function-app-dev
  - ${{ if and(ne(variables['Build.Reason'], 'PullRequest'), startsWith(variables['Build.SourceBranch'], 'refs/heads/release/')) }}:
    - group: function-app-test
  - ${{ if and(ne(variables['Build.Reason'], 'PullRequest'), eq(variables['Build.SourceBranchName'], 'main')) }}:
    - group: function-app-prd

stages:
  # Build Stage (also handles PR validation)
  - stage: Build
    displayName: ${{ eq(variables['Build.Reason'], 'PullRequest') && 'PR Validation' || 'Build Application' }}
    jobs:
      - job: Build
        displayName: ${{ eq(variables['Build.Reason'], 'PullRequest') && 'Validate Function App' || 'Build Function App' }}
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          # Build Application with automatic versioning and git tagging
          # For PRs: runs tests and linting only (no versioning/tagging)
          # For deployments: runs full build with versioning and tagging
          - template: templates/build-template.yml@templates
            parameters:
              pythonVersion: $(pythonVersion)
              workingDirectory: $(workingDirectory)
              artifactName: $(artifactName)
              runTests: ${{ eq(variables['Build.Reason'], 'PullRequest') }}
              runLinting: ${{ eq(variables['Build.Reason'], 'PullRequest') }}

  # Deploy to Dev (automatic for develop branch)
  - template: templates/deploy-environment-template.yml@templates
    parameters:
      environmentName: 'dev'
      azureSubscription: $(azureSubscription)
      appName: $(appName)
      slotName: 'staging'
      artifactName: $(artifactName)
      resourceGroup: $(resourceGroup)
      appType: 'functionApp'
      dependsOn: ['Build']
      condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'), eq(variables['Build.SourceBranchName'], 'develop'))

  # Deploy to Test (automatic for release/* branches)
  - template: templates/deploy-environment-template.yml@templates
    parameters:
      environmentName: 'test'
      azureSubscription: $(azureSubscription)
      appName: $(appName)
      slotName: 'staging'
      artifactName: $(artifactName)
      resourceGroup: $(resourceGroup)
      appType: 'functionApp'
      dependsOn: ['Build']
      condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'), startsWith(variables['Build.SourceBranch'], 'refs/heads/release/'))

  # Deploy to Production (automatic for main branch, requires environment approval)
  - template: templates/deploy-environment-template.yml@templates
    parameters:
      environmentName: 'prd'
      azureSubscription: $(azureSubscription)
      appName: $(appName)
      slotName: 'staging'
      artifactName: $(artifactName)
      resourceGroup: $(resourceGroup)
      appType: 'functionApp'
      dependsOn: ['Build']
      condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'), eq(variables['Build.SourceBranchName'], 'main'))
